spring.application.name=online_store
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.thymeleaf.cache=false
spring.jpa.defer-datasource-initialization=true
# JWT
jwt.secret=eW91clN1cGVyU2VjcmV0S2V5Rm9ySldUQXRMZWFzdDI1NkJpdHNMb25nSGVyZTEyMzQ1Njc4OTA=
jwt.expiration=86400000

# Security
spring.security.filter.order=1